import { TransactionsPixProvider } from '@/contexts/TransactionsPixContext'
import NextAuthSessionProvider from '@/providers/sessionProvider'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Pix Generator App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradiente-linear-black-ofCourse ">
        <NextAuthSessionProvider>
          <TransactionsPixProvider>{children}</TransactionsPixProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
